{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $svc.port }}
          resources:
            limits:
              cpu: {{ $.Values.resources.limits.cpu | quote }}
              memory: {{ $.Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ $.Values.resources.requests.cpu | quote }}
              memory: {{ $.Values.resources.requests.memory | quote }}
      imagePullSecrets:
        - name: {{ $.Values.global.imagePullSecrets }}
      {{- if $svc.nodeSelector }}
      nodeSelector:
        {{- toYaml $svc.nodeSelector | nindent 8 }}
      {{- end }}
{{- end }}

